name 'sample-app'
maintainer 'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_COMPANY_EMAIL' 
license 'All rights reserved'
description 'Installs/Configures sample-app'
long_description 'Installs/Configures sample-app'
version '0.1.0'
